name: Build and deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Update NPM
        run: |
          npm install -g npm@latest
      - name: Install, build and deploy
        run: |
          npm ci
          npm run deploy
